<a href="./file_include.php?language=zh-cn">Switch to Chinese</a>
<article class="am-article am-margin-top-lg">
    <div class="am-article-hd">
        <h1 class="am-article-title">The "population balance" is insufficient: the upper population limit of the four first tier cities is 4.116 million</h1>
        <p class="am-article-meta">Guangdong 21st century global economic news, creator of high-quality financial field</p>
    </div>

    <div class="am-article-bd">
        <p class="am-article-lead">21st Century Business Herald reporter Chen Jie intern Du Bohan reports from Guangzhou and Beijing
            For some cities, the "balance" of population growth is running out.
            The so-called "population balance" refers to the difference between the future resident population scale target set in each urban planning and the current resident population scale.
            According to the statistics of the 21st Century Business Herald, the first tier cities, new first tier cities and provincial capitals with urban planning and land and space planning have been released. At least 11 cities have issued corresponding plans or draft for comments, but the "population balance" of some cities is low. Taking the first tier cities as an example, the overall "population balance" is only 4115900.
            "The trend of population gathering in big cities will not change fundamentally in the future. The 'balance' of the permanent population in the first tier cities is not much, but the surrounding satellite cities still have enough incremental space. I think the first tier cities will give play to the effect of population distribution in the future. When the national population gradually gathers, the first tier cities will evacuate to the surrounding areas, so the satellite cities around the first tier cities in recent years Rapid development, "sun Busu, vice president of South China Urban Research Association, told the 21st Century Business Herald.
            Insufficient "population balance" in first tier cities
            In the future, how much room does the population of big cities have to rise?
            From the perspective of cities that have released relevant plans at present, "population balance" is different. The "population balance" of first tier cities is relatively insufficient, of which Shanghai has basically reached the upper limit of population planning, and the "population balance" of Beijing, Guangzhou and Shenzhen is also less than 1.5 million.
            Specifically, according to the overall urban planning of Shanghai (2017-2035), the scale of about 25 million people is taken as the regulation target of permanent population in 2035. By 2050, the scale of permanent resident population will remain stable. The 2020 Shanghai census shows that its population has reached 24.8709 million. In other words, if the target is 25 million, Shanghai's "population balance" is only 129100.
            According to the Beijing urban master plan (2016-2035), the permanent resident population will be controlled within 23 million by 2020. After strict control of the new population and the relief of non capital functions, according to the 2020 census, the population of Beijing has reached 21.893 million and the "population balance" is 1.107 million.
            The "population balance" of Guangzhou and Shenzhen is relatively more. According to the master plan of Guangzhou (2017-2035), the permanent resident population of Guangzhou will be controlled at about 20 million in 2035. In 2020, the permanent resident population of Guangzhou was 18.6766 million, and the "population balance" was 132.34 million. The overall land and space planning of Shenzhen (2020-2035) proposes that the permanent resident population will be 19 million in 2035. In 2020, the permanent resident population of Shenzhen will be 17.5601 million, and the "population balance" will be 1.4399 million.
            This means that the "balance" of the overall resident population of the four first tier cities is only 4115900. Does this mean that the population scale of first tier cities will slow down in the future?
            Sun Busu pointed out that according to relevant plans, we can see that the wording of different places is different. For example, Beijing proposes to control within 23 million people, Shanghai proposes a scale of about 25 million people, and "about" means that there is room for maneuver. The wording of Guangzhou and Shenzhen is different. They propose to allocate infrastructure and public services according to the actual management and service population. In 2035, Shenzhen proposes 23 million actual management and service population and Guangzhou proposes 25 million. Therefore, in fact, there is sufficient adjustment space on the basis of population control.
            "Moreover, from the example of Shenzhen, it is not easy to say whether these plans have rigid restrictions on the urban population, because almost every resident population in Shenzhen has exceeded the previous plans in the past development process," Sun said.
            However, a noteworthy signal is that recently, Shenzhen has tightened the entry threshold, and the minimum entry requirements for educated talents are full-time undergraduates.
            "This actually reveals a signal that the large-scale 'human robbery' in Chinese cities has entered a subtle turning point. Behind it is that the limit of urban population is getting closer and closer, because it is difficult for cities to expand indefinitely," Sun said.
            He pointed out that urban population size and urban economy have a diminishing effect of scale. When a city reaches the growth margin, there will be diseconomy of scale, that is, the increase of population has little improvement on urban efficiency, but it will bring huge costs, such as traffic congestion, high housing prices, air pollution and other problems.
            "Taking international big cities as an example, New York once ushered in a stage of large-scale population expansion, but when the total population reached 8 million, the growth rate of New York's population slowed down significantly, and the city did not issue policies to control the population scale. For China, Shanghai is almost the limit standard of urban scale, so when the total population of a city reaches 20 million , we can see the growth bottleneck. At this time, the government regulation is to follow the trend, "said Sun Busu.
            Zhang Dawei, chief analyst of Centaline real estate, told the 21st Century Business Herald that the small "balance" of population rise in first tier cities will also have an impact on real estate, but it also depends on the implementation of local policies. Relatively speaking, the implementation in Beijing is relatively strict.
            "However, for real estate, it depends not only on the total population, but also on the quality of the population. If more talents flow in, even if the total population decreases, it may mean that more people have the demand for house purchase for real estate," Zhang Dawei said.
            There is still room for population improvement in the provincial capital
            Compared with the insufficient "population balance" of first tier cities, many new first tier cities and provincial capitals still have large space for population growth.
            At the end of September, the overall land and space planning of Tianjin (2021-2035) (Draft for comments) was released, which proposed that the planned population of Tianjin in 2035 should be controlled at about 20 million. This means that there is still much room for population growth in Tianjin. According to the latest census data, the total population of Tianjin will be 13.866 million in 2020, and the population growth of Tianjin can exceed 40% in the future.
            Suzhou is similar to Tianjin. According to the overall land and space planning of Suzhou (2021-2035), by 2035, the permanent resident population of Suzhou will be 17-18 million. Compared with the population census of 12.7483 million in 2020, this data also has more than 40% growth space.
            In addition to Tianjin and Suzhou, according to the overall urban planning of Nanjing (2018-2035), the permanent resident population of the city will be controlled within 13 million by 2035, which will be stable for a long time after 2035. In 2020, the permanent resident population of Nanjing will be 9.3147 million.
            According to the overall land and space planning of Hangzhou (2021-2035), the permanent resident population will be about 15 million by 2035. In 2020, the permanent resident population of Hangzhou will be 11.936 million.
            The overall land and space planning of Chengdu (2020-2035) determines that the permanent resident population will be controlled at 24 million in 2035. According to the census data of 2020, the total population of Chengdu is 20937800. This means that there is still a large space for population growth in Chengdu in the future.
            Sun Busu believes that compared with Beijing, Shanghai, Guangzhou and Shenzhen, more people in Chengdu are not concentrated in the central urban area, but sink to the suburbs and county-level cities. However, the population pressure in the central urban area of first tier cities is too large, and Chengdu has relatively more room for population maneuver.
            In addition, the overall land and space planning of Wuhan (2021-2035) proposes that by 2035, the planning can accommodate 16.6 million permanent residents. In 2020, the total population of Wuhan will be 12.3265 million. According to the overall land and space planning of Fuzhou (2021-2035), by 2035, the permanent resident population of Fuzhou will be 10 million. In 2020, the permanent resident population of Fuzhou will be 8.2913 million.
            This means that in addition to the first tier cities, other big cities still have 15% - 45% of the permanent population growth space. What impact will this have?
            Sun Busu pointed out that the relevant plans of some cities show that there is still a large room for population growth, but this only means that there is still a large room for population growth in these cities, which does not mean that they must attract so many people. In addition, these cities will not immediately build infrastructure and public services to meet population planning, but will dynamically adjust according to the current situation.
            This does not mean that city with larger population space will release the registered residence in one step.
            "Take Tianjin as an example, Tianjin is a municipality directly under the central government, and it has the" college entrance examination benefits ". In recent years, many people who work in Beijing but can not get Beijing registered residence have settled their accounts to Tianjin. Therefore, if Tianjin really lets go of the household registration, it will be more attractive to the population, but it does not meet the needs of the city. Satellite cities in many big cities now have more opportunities.
            Zhang Dawei pointed out that at present, the attraction of big cities is still increasing, and it is necessary to prevent the tendency of excessive real estate in satellite cities around big cities. Because if the satellite city lacks industrial support, most of the incoming population's demand for house purchase is for investment and speculation, which is unfavorable to the local development.
            "At present, satellite cities are more speculative demand and do not form a benign real estate market. Therefore, once there is fluctuation, it will have a great impact on these satellite cities. In addition, large cities need to further build rail transit to connect the surrounding areas." Zhang Dawei said.</p>
    </div>
</article>